first-active-range = [0, 70]
active-window-range = [0, 20]
min-stable-interval = 15

max-stable-pop = 100
max-active-cells = 100

stabilise-results = true

pattern = '''
x = 22, y = 21, rule = LifeHistory
.A$2.A$3A$5.A$6.A$4.3A$9.A$10.A$8.3A$13.A$14.A$12.3A3$15.7B$15.7B$15.
7B$15.7B$15.7B$15.7B$15.7B!
'''
