first-active-range = [3, 15]
active-window-range = [0, 20]
min-stable-interval = 4

max-active-cells = 14
ever-active-bounds = [7, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 24, y = 30, rule = LifeHistory
8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$9.15B$9.
15B$4.3A2.15B$4.3A2.15B$3.A3.A.15B$4.3A2.15B$4.3A2.15B$2A7.15B$2A7.
15B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B$8.16B
!
'''
